# Generated by Django 5.1.4 on 2025-01-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_book_category_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(max_length=200, default=''),
        ),
    ]
