# Generated by Django 6.0.3 on 2026-03-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_book_authors_alter_book_distribution_expense_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='book',
            table='tracker_book',
        ),
    ]
