# Generated by Django 6.0.3 on 2026-03-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_book_unique_together_alter_book_table'),
        ('tracker', '0008_auto_20260327_1447'),
    ]

    operations = [
    ]
